import type { Metadata } from "next";
import { HeroProvider } from "./HeroProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <HeroProvider>{children}</HeroProvider>
      </body>
    </html>
  );
}
