import express from "express";
import { applicationIdentityRuntime, resolveApplicationIdentity } from "../applicationIdentity/applicationIdentityMiddleware.ts";
import { ApplicationIdentityDatabase } from "../applicationIdentity/applicationIdentityDatabase.ts";
import { buildErrorResponse, buildSuccessResponse } from "../utils/responseHandler.ts";
import { resolveCurrentApplicationActor } from "../reservation/currentApplicationActor.ts";
import { ReservationApprovalService } from '../reservationApproval/reservationApprovalService.ts';
const router=express.Router(); router.use(express.json()); router.use(resolveApplicationIdentity);
function cookieOptions(expires:Date){ const {config}=applicationIdentityRuntime(); return {httpOnly:true,sameSite:"lax" as const,path:"/",secure:config.production,expires}; }
router.get('/session',async(req,res)=>{ const {config}=applicationIdentityRuntime(); if(!req.applicationIdentity){ if(config.mode==='disabled') return buildSuccessResponse(res,200,{accountUuid:null,accountKey:resolveCurrentApplicationActor(),displayLabel:'Legacy development fallback',accountStatus:'active',expiresAt:null,provider:'legacy_development_fallback',assurance:'development_only',applicationArea:'student'}); return buildErrorResponse(res,401,'No active application session.'); } const i=req.applicationIdentity; const area=await new ApplicationIdentityDatabase().applicationArea(i.accountId); buildSuccessResponse(res,200,{accountUuid:i.accountUuid,accountKey:i.accountKey,displayLabel:i.displayLabel,accountStatus:i.accountStatus,expiresAt:i.expiresAt,provider:i.provider,assurance:i.authenticationAssurance,applicationArea:area}); });
router.get('/local-accounts',async(_req,res)=>{ const {config}=applicationIdentityRuntime(); if(!config.localLoginEnabled||config.production) return buildErrorResponse(res,404,'Local synthetic login is unavailable.'); const rows=await new ApplicationIdentityDatabase().listLocalAccounts(); buildSuccessResponse(res,200,rows.map(x=>({accountUuid:x.account_uuid,accountKey:x.account_key,displayLabel:x.display_label,status:x.status}))); });
router.post('/local-login',async(req,res)=>{ try { const {provider,config}=applicationIdentityRuntime(); if(!provider||config.mode!=="local_session") return buildErrorResponse(res,403,'Local synthetic login is disabled.'); const session=await provider.createLocalSession(String(req.body?.accountKey??'')); res.cookie(config.cookieName,session.token,cookieOptions(session.expiresAt)); buildSuccessResponse(res,201,{accountUuid:session.account.account_uuid,accountKey:session.account.account_key,displayLabel:session.account.display_label,expiresAt:session.expiresAt.toISOString(),provider:'local_synthetic_session',assurance:'development_only'}); } catch(error:any){ buildErrorResponse(res,error.httpStatus??400,error.message??'Local login failed.'); } });
router.post('/logout',async(req,res)=>{ const {provider,config}=applicationIdentityRuntime(); if(req.applicationIdentity) await new ReservationApprovalService().endSessionReviews(req.applicationIdentity.sessionUuid); if(provider) await provider.revokeSession(req); res.clearCookie(config.cookieName,{httpOnly:true,sameSite:'lax',path:'/',secure:config.production}); buildSuccessResponse(res,200,{revoked:true}); });
export default router;
