"use client";

import { useMemo, useState } from "react";
import { Button } from "@heroui/react";

type Props = { asset: any; actorId: string; onClose: () => void };
function message(json: any, fallback: string) { return json?.message ?? json?.error ?? fallback; }
function stateLabel(value: string | undefined) { return value === "available" ? "Disponível" : value === "eligible" ? "Sem alertas" : value === "not_eligible" ? "Requer atenção" : value === "conflict" ? "Conflito" : value ?? "Não disponível"; }

export default function ReservationModal({ asset, actorId, onClose }: Props) {
  const [startDate, setStartDate] = useState(""); const [startTime, setStartTime] = useState(""); const [endDate, setEndDate] = useState(""); const [endTime, setEndTime] = useState("");
  const [evidence, setEvidence] = useState<any | null>(null); const [legacyAvailable, setLegacyAvailable] = useState<boolean | null>(null); const [error, setError] = useState<string | null>(null); const [checking, setChecking] = useState(false); const [creating, setCreating] = useState(false); const [shadowConfirmed, setShadowConfirmed] = useState(false);
  const start = useMemo(() => startDate && startTime ? `${startDate}T${startTime}` : "", [startDate, startTime]); const end = useMemo(() => endDate && endTime ? `${endDate}T${endTime}` : "", [endDate, endTime]);
  const invalidate = () => { setEvidence(null); setLegacyAvailable(null); setError(null); setShadowConfirmed(false); };
  function validateInputs() { if (!actorId || !start || !end) return "Indique o intervalo pretendido."; if (new Date(end) <= new Date(start)) return "O fim tem de ser posterior ao início."; if (new Date(start) <= new Date()) return "O início não pode estar no passado."; return null; }
  async function legacyAvailability() { const response = await fetch(`/api/asset/availability/${asset.id}?start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}`); const json = await response.json().catch(() => null); if (!response.ok) throw new Error(message(json, "Não foi possível verificar a disponibilidade.")); setLegacyAvailable(Boolean(json?.data?.available)); }
  async function checkEvidence() { const invalid = validateInputs(); if (invalid) { setError(invalid); return; } setChecking(true); setError(null); setEvidence(null); setLegacyAvailable(null); setShadowConfirmed(false); try { const response = await fetch("/api/reservation/evidence", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assetId: asset.id, start, end }) }); const json = await response.json().catch(() => null); if (response.status === 503 || response.status === 404) await legacyAvailability(); else if (!response.ok) throw new Error(message(json, "Não foi possível reunir a evidência.")); else setEvidence(json?.data ?? json); } catch (cause: any) { setError(cause?.message ?? "Não foi possível reunir a evidência."); } finally { setChecking(false); } }
  async function createReservation() { const invalid = validateInputs(); if (invalid) { setError(invalid); return; } setCreating(true); setError(null); try { const response = await fetch("/api/reservation/request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assetId: asset.id, startTime: start, endTime: end, semanticEvidenceRunUuid: evidence?.runUuid ?? undefined }) }); const json = await response.json().catch(() => null); if (!response.ok) throw new Error(message(json, "O pedido não foi criado.")); const result = json?.data ?? json; alert(`Pedido de reserva criado com o estado ${result?.status ?? "pending"}.`); onClose(); } catch (cause: any) { setError(cause?.message ?? "O pedido não foi criado."); } finally { setCreating(false); } }
  const needsAcknowledgement = evidence && evidence.semanticEligibility?.outcome !== "eligible"; const canCreate = Boolean(evidence || legacyAvailable) && (!needsAcknowledgement || shadowConfirmed);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded bg-white p-6 shadow-lg"><h3 className="mb-1 text-lg font-semibold">Novo pedido: {asset.name}</h3><p className="mb-4 text-sm text-slate-600">Indique o intervalo, verifique a evidência e submeta o pedido. A confirmação final de disponibilidade é feita quando o pedido é decidido.</p>
    <div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Conta atual<input className="w-full rounded border bg-slate-50 p-2" readOnly value={actorId} /></label><label className="text-sm">Recurso<input className="w-full rounded border bg-slate-50 p-2" readOnly value={asset.name} /></label><DateTime label="Início" date={startDate} time={startTime} setDate={(value: string) => { setStartDate(value); invalidate(); }} setTime={(value: string) => { setStartTime(value); invalidate(); }} /><DateTime label="Fim" date={endDate} time={endTime} setDate={(value: string) => { setEndDate(value); invalidate(); }} setTime={(value: string) => { setEndTime(value); invalidate(); }} /></div>
    <Button className="mt-4" color="secondary" onPress={checkEvidence} isLoading={checking}>Verificar evidência</Button>{error && <div className="mt-3 rounded bg-red-100 p-3 text-red-800">{error}</div>}{legacyAvailable !== null && <div className={`mt-3 rounded p-3 ${legacyAvailable ? "bg-green-100" : "bg-red-100"}`}>Disponibilidade atual: <b>{legacyAvailable ? "Disponível" : "Conflito"}</b></div>}{evidence && <EvidenceResult evidence={evidence} />}
    {needsAcknowledgement && <label className="mt-4 flex gap-2 rounded bg-amber-50 p-3 text-sm"><input type="checkbox" checked={shadowConfirmed} onChange={(event) => setShadowConfirmed(event.target.checked)} />Reconheço o alerta apresentado e pretendo submeter o pedido.</label>}
    <div className="mt-5 flex justify-between"><Button variant="light" onPress={onClose}>Fechar</Button><Button color="primary" onPress={createReservation} isLoading={creating} isDisabled={!canCreate}>Criar pedido</Button></div>
  </div></div>;
}
function DateTime({ label, date, time, setDate, setTime }: any) { return <label className="text-sm">{label}<div className="flex gap-2"><input type="date" className="w-1/2 rounded border p-2" value={date} onChange={(event) => setDate(event.target.value)} /><input type="time" className="w-1/2 rounded border p-2" value={time} onChange={(event) => setTime(event.target.value)} /></div></label>; }
function EvidenceResult({ evidence }: { evidence: any }) { const findings = evidence.semanticEligibility?.findings ?? []; return <div className="mt-4 space-y-3 text-sm"><section className="rounded border p-3"><h4 className="font-semibold">Resultado da evidência</h4><p className="mt-1">Contexto institucional: <b>{stateLabel(evidence.actorEvidence?.status)}</b></p><p>Validação estrutural: <b>{stateLabel(evidence.structuralEvidence?.status)}</b></p><p>Resultado semanticamente informado: <b>{stateLabel(evidence.semanticEligibility?.outcome)}</b></p><p>Disponibilidade atual: <b>{stateLabel(evidence.availability?.status)}</b></p>{evidence.availability?.conflicts?.map((conflict: any, index: number) => <p className="mt-1 text-red-700" key={index}>{conflict.message}</p>)}</section><details className="rounded border p-3"><summary>Detalhes técnicos e proveniência</summary><div className="mt-2 space-y-1"><p>Recurso: {evidence.resourceEvidence?.tag ?? "não disponível"} · {evidence.resourceEvidence?.location ?? "sem localização"}</p><p>Política: {evidence.semanticEligibility?.policyFilename ?? "não disponível"}</p><p>Validação: {evidence.structuralEvidence?.shapesVersion ?? "não disponível"}</p>{findings.map((finding: any, index: number) => <p className="text-red-700" key={index}>{finding.message}</p>)}</div></details></div>; }
