"use client";

import { useEffect, useState } from "react";
import ManagerNavigation from "../ManagerNavigation";
import { ApiResponseError, parseApiJsonResponse } from "@/lib/apiResponse.mts";
import { formatLisbonDateTime, lisbonTimeZoneLabel } from "@/lib/lisbonDateTime";

type Row = { id: number; status: string; asset_code: string; name: string; start_time: string; end_time: string; actor_id: string; shadow_eligibility_outcome: string | null; sql_availability_status: string | null; reason: string | null; };
type Review = { status: "current" | "stale" | "expired" | "session_ended" | "failed"; run_uuid?: string; reviewed_at?: string; expires_at?: string; stale_reason?: string | null; actor_link_id?: number | null; institutional_artifact_id?: number | null; model_version_id?: number | null; materialisation_id?: number | null; structural_validation_run_id?: number | null; policy_artifact_id?: number | null; shadow_eligibility_outcome?: string | null; sql_availability_status?: string | null; };
type UiError = { message: string; details: string; code: string };

function uiError(error: unknown): UiError {
  if (error instanceof ApiResponseError) return { message: error.message, details: error.technicalDetails, code: error.code };
  return { message: "Não foi possível concluir a operação. Tente novamente.", details: "Erro inesperado do cliente; nenhum conteúdo do servidor foi exposto.", code: "technical_error" };
}
function reviewState(value: Review | undefined) {
  if (!value) return "ausente";
  if (value.status === "current" && value.expires_at && new Date(value.expires_at).getTime() <= Date.now()) return "expirada";
  return ({ current: "atual", stale: "desatualizada", expired: "expirada", session_ended: "sessão terminada", failed: "falhou" } as const)[value.status];
}
function statusLabel(value: string) { return ({ pending: "Pendente", approved: "Aprovada", rejected: "Rejeitada", cancelled: "Cancelada", in_use: "Em utilização", completed: "Concluída" } as Record<string, string>)[value] ?? value; }
function shadowLabel(value: string | null | undefined) { return value === "eligible" ? "Sem alertas" : value === "not_eligible" ? "Requer atenção" : value === "indeterminate" ? "Indeterminada" : "Ainda não verificada"; }
function availabilityLabel(value: string | null | undefined) { return value === "available" ? "Disponível" : value === "conflict" ? "Conflito" : "Será confirmada ao decidir"; }

export default function ReservationManagement() {
  const [rows, setRows] = useState<Row[]>([]); const [error, setError] = useState<UiError | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [reason, setReason] = useState<Record<number, string>>({}); const [acknowledged, setAcknowledged] = useState<Record<number, boolean>>({}); const [review, setReview] = useState<Record<number, Review>>({}); const [busy, setBusy] = useState<Record<number, boolean>>({});
  const [statusFilter, setStatusFilter] = useState("pending"); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ page: 1, pageSize: 25, totalItems: 0, totalPages: 1 });
  const load = async (requestedPage = page, requestedStatus = statusFilter) => {
    try { const response = await fetch(`/api/manager/reservations?page=${requestedPage}&pageSize=25&status=${requestedStatus}`, { cache: "no-store" }); const payload = await parseApiJsonResponse<{ items: Row[]; page: number; pageSize: number; totalItems: number; totalPages: number }>(response); setRows(payload.data.items); setPagination(payload.data); setPage(payload.data.page); setError(null); }
    catch (caught) { setError(uiError(caught)); }
  };
  useEffect(() => { void load(page, statusFilter); }, [page, statusFilter]);
  const openDetail = async (id: number, refresh = false) => {
    setBusy((current) => ({ ...current, [id]: true })); setError(null); setNotice(null);
    try { const response = await fetch(`/api/manager/reservations/${id}${refresh ? "/refresh-evidence" : ""}`, { method: refresh ? "POST" : "GET", headers: { Accept: "application/json" } }); const payload = await parseApiJsonResponse<{ reviewEvidence: Review; refreshed: boolean }>(response); setReview((current) => ({ ...current, [id]: payload.data.reviewEvidence })); setNotice(refresh ? `Evidência atualizada às ${formatLisbonDateTime(payload.data.reviewEvidence.reviewed_at!)}. Nenhuma decisão foi tomada.` : `Análise aberta para o pedido ${id}. Nenhuma decisão foi tomada.`); await load(); }
    catch (caught) { setError(uiError(caught)); setReview((current) => current[id] ? current : ({ ...current, [id]: { status: "failed" } })); }
    finally { setBusy((current) => ({ ...current, [id]: false })); }
  };
  const decide = async (id: number, action: "approve" | "reject" | "cancel") => {
    setBusy((current) => ({ ...current, [id]: true })); setError(null); setNotice(null);
    try { const response = await fetch(`/api/manager/reservations/${id}/${action}`, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ reason: reason[id] ?? "", overrideAcknowledged: acknowledged[id] === true }) }); await parseApiJsonResponse(response); setNotice(`Pedido ${id} ${action === "approve" ? "aprovado" : action === "reject" ? "rejeitado" : "cancelado"}.`); await load(); }
    catch (caught) { const nextError = uiError(caught); setError(nextError); if (nextError.code === "review_evidence_stale") setReview((current) => current[id] ? ({ ...current, [id]: { ...current[id], status: "stale" } }) : current); if (nextError.code === "review_evidence_required") setReview((current) => { const next = { ...current }; delete next[id]; return next; }); }
    finally { setBusy((current) => ({ ...current, [id]: false })); }
  };
  return <main className="uminho-page p-5 sm:p-8"><ManagerNavigation />
    <header><p className="text-sm font-semibold uppercase tracking-[.22em]" style={{ color: "var(--uminho-primary)" }}>Workspace do gestor</p><h1 className="mt-2 text-3xl font-bold">Reservas e decisões</h1><p className="mt-2 max-w-3xl" style={{ color: "var(--text-secondary)" }}>Abra uma análise para atualizar a evidência do pedido. Só então pode aprovar, rejeitar ou cancelar.</p></header>
    <div className="uminho-card mt-5 flex flex-wrap items-center gap-3 p-3"><label>Estado: <select className="uminho-input ml-2 p-2" value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); setPage(1); }}><option value="pending">Pendentes</option><option value="all">Todos</option><option value="approved">Aprovadas</option><option value="rejected">Rejeitadas</option><option value="cancelled">Canceladas</option><option value="in_use">Em utilização</option><option value="completed">Concluídas</option></select></label><span className="text-sm" style={{ color: "var(--text-secondary)" }}>{rows.length} de {pagination.totalItems} pedidos</span><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Anterior</button><span className="text-sm">Página {page} de {pagination.totalPages}</span><button disabled={page >= pagination.totalPages} onClick={() => setPage(page + 1)}>Seguinte</button><button onClick={() => load(page, statusFilter)}>Atualizar fila</button></div>
    {error && <div className="uminho-banner uminho-banner-error mt-4" role="alert"><span aria-hidden="true">!</span><div><p className="font-semibold">Não foi possível concluir a operação</p><p>{error.message}</p><details className="mt-2 text-sm"><summary>Detalhes técnicos</summary><code>{error.details}</code></details></div></div>}{notice && <p className="uminho-banner uminho-banner-success mt-4" role="status"><span aria-hidden="true">✓</span><span>{notice}</span></p>}
    <div className="mt-6 space-y-4">{rows.map((row) => { const evidence = review[row.id]; const state = reviewState(evidence); const reviewOutcome = evidence?.shadow_eligibility_outcome ?? row.shadow_eligibility_outcome; const needsOverride = reviewOutcome === "not_eligible" || reviewOutcome === "indeterminate"; const reasonPresent = Boolean(reason[row.id]?.trim()); const reviewReady = row.status === "pending" && state === "atual" && !busy[row.id]; const canReject = reviewReady && reasonPresent; const canApprove = reviewReady && (!needsOverride || (acknowledged[row.id] === true && reasonPresent));
      return <article className="uminho-card p-4" key={row.id}><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-bold">{row.name || row.asset_code}</h2><p className="text-sm text-slate-300">Pedido {row.id} · {statusLabel(row.status)}</p></div><p className="text-sm">{formatLisbonDateTime(row.start_time)} — {formatLisbonDateTime(row.end_time)} <span className="text-slate-400">({lisbonTimeZoneLabel})</span></p></div>
        <div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p>Requerente: {row.actor_id}</p><p>Resultado da evidência: <b>{shadowLabel(reviewOutcome)}</b></p><p>Disponibilidade atual: <b>{availabilityLabel(evidence?.sql_availability_status ?? row.sql_availability_status)}</b></p></div>
        <p className={`uminho-banner mt-3 text-sm ${state === "atual" ? "uminho-banner-success" : state === "ausente" ? "uminho-banner-info" : "uminho-banner-warning"}`} id={`review-state-${row.id}`}><span aria-hidden="true">{state === "atual" ? "✓" : "i"}</span><span>Estado da análise: <b>{state}</b>{state === "ausente" && " — abra o pedido antes de decidir."}{state === "sessão terminada" && " — abra uma nova análise nesta sessão."}{(state === "desatualizada" || state === "expirada") && " — atualize a evidência antes de decidir."}{state === "falhou" && " — tente abrir ou atualizar a análise."}</span></p>
        <div className="mt-3 flex flex-wrap gap-2">{(state === "ausente" || state === "sessão terminada" || state === "falhou") && <button disabled={busy[row.id]} onClick={() => openDetail(row.id)}>Abrir análise</button>}{state !== "ausente" && state !== "sessão terminada" && <button disabled={busy[row.id]} onClick={() => openDetail(row.id, true)}>Atualizar evidência</button>}</div>
        {evidence?.run_uuid && <details className="uminho-details mt-3 text-sm"><summary>Evidência utilizada e proveniência</summary><p className="mt-2">Atualizada em {formatLisbonDateTime(evidence.reviewed_at!)} para a sessão atual.</p><dl className="mt-2 grid gap-1 sm:grid-cols-2"><div>Resultado: {shadowLabel(evidence.shadow_eligibility_outcome)}</div><div>Disponibilidade: {availabilityLabel(evidence.sql_availability_status)}</div><div>Motivo de atualização: {evidence.stale_reason ?? "nenhum"}</div><div>Expira: {evidence.expires_at ? formatLisbonDateTime(evidence.expires_at) : "não indicado"}</div><div>Execução: {evidence.run_uuid}</div><div>Versão do modelo: {evidence.model_version_id ?? "não disponível"}</div></dl></details>}
        {["pending", "approved"].includes(row.status) && <div className="mt-4 flex flex-wrap gap-2"><input className="min-w-72 rounded bg-slate-950 p-2" placeholder="Razão (obrigatória para rejeitar, cancelar ou aprovar com alerta)" value={reason[row.id] ?? ""} onChange={(event) => setReason({ ...reason, [row.id]: event.target.value })} />{row.status === "pending" && needsOverride && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={acknowledged[row.id] === true} onChange={(event) => setAcknowledged({ ...acknowledged, [row.id]: event.target.checked })} />Reconheço o alerta da evidência para aprovar</label>}{row.status === "pending" && <><button aria-describedby={`review-state-${row.id}`} disabled={!canApprove} onClick={() => decide(row.id, "approve")}>Aprovar</button><button aria-describedby={`review-state-${row.id}`} disabled={!canReject} onClick={() => decide(row.id, "reject")}>Rejeitar</button></>}<button disabled={busy[row.id]} onClick={() => decide(row.id, "cancel")}>Cancelar</button></div>}
        {row.status === "pending" && state === "atual" && !reasonPresent && <p className="uminho-banner uminho-banner-warning mt-2 text-sm"><span aria-hidden="true">!</span><span>Indique uma razão para rejeitar. Se houver alerta na evidência, a aprovação também requer razão e confirmação.</span></p>}{row.reason && <p className="mt-3 text-sm">Razão da decisão: {row.reason}</p>}</article>; })}</div>
  </main>;
}
